services:
  - "ВНЛЗ":
      title: "ВНЛЗ"
      color: "#0a58ca"
  - "СЗ":
      title: "Служба зв'язку"
      color: "green"

categories:
  - 'computers'
  - 'projectors'
  - 'communications'
  - 'СЕДО'
  - 'software'
