# Перелік служб та кольори відображення
services:
  - "ВНЛЗ":
      title: "ВНЛЗ"
      color: "#0a58ca"
  - "СЗ":
      title: "Служба зв'язку"
      color: "green"

# Перелік категорій для фільтрів та їх відображення
# Зверніть увагу, що для коректної роботи фільтрації по категоріям, в базі даних мають бути записані
# категорії відповідно до цього переліку (наприклад, "computers", "projectors", "communications", "СЕДО", "software")
categories:
  "computers": "Комп'ютери"
  "projectors": "Проектори"
  "communications": "Комм. обладнання"
  "СЕДО": "Обладнання СЕДО"
  "software": "Програмне забезпечення"

additionalFilters:
  filterByYear: true
  filterNoService: true